### ISSUE TITLE
Gauges won't knit ("CSS" related error) 

### ISSUE THREAD

**Issue by TTT12-dumb-dumb** [rstudio/flexdashboard#282] opened 2020-09-28 01:40 UTC
Hi. when trying to knit a document that was created from the flexdashboard template, with no changes and nothing written other than `gauge(50, 0, 100)`, I receive the following error:

 
Error in validateCssUnit(sizeInfo$width) : 
  CSS units must be a single-element numeric or character vector
Calls: <Anonymous> ... <Anonymous> -> need_screenshot -> toHTML -> validateCssUnit
Execution halted

When running the chunk by itself, the gauge is outputted as expected.  Apologies if this has been addressed before but I could find nothing in either the documentation or through searching.  Thanks.

**Comment by cderv** [comment] 2020-09-28 12:29
If I try to reproduce following
>Hi. when trying to knit a document that was created from the flexdashboard template, with no changes and nothing written other than gauge(50, 0, 100)

<details><summary>I get this document </summary>

````md
---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
gauge(50, 0, 100)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

````
</details>

and it works ok.

Can you share you source code ? Wild guess: Do you have a htmlwidget in your document ? like plotly or DT or leaflet or other ?

Because it could be related to an issue between knitr, flexdashboard and htmlwidget.

**Comment by TTT12-dumb-dumb** [comment] 2020-09-28 19:53
Hi, thanks for responding!  This is the code i'm working with:

<details><summary>flexdashboard template with only a gauge written in</summary>

````
---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
gauge(60,0,100)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```
````
</details>

Here's a screenshot of my Rstudio as well.  

![image](https://user-images.githubusercontent.com/53317737/94479058-34f91180-01a2-11eb-89a0-b0461c82e0d6.png)

Something else to note while I was playing around with things: you are correct in that when I (in a separate file) tried to include a `plotly` object via `ggplotly`, I received the same error message (I had removed any gauges for this attempt).  I managed to get the document to knit when I included a specific width and height setting in the `ggplotly` configuration.  I'm not sure if that provides any hints?

Though, of course, I'd prefer to not have to set a specific width/height dimension for any `plotly` plots either.  

Thanks!

**Comment by cderv** [comment] 2020-09-30 09:19
Ok so this is the same bug as https://github.com/yihui/knitr/issues/1901 and a suggest fix is in **htmlwidgets** 
https://github.com/ramnathv/htmlwidgets/pull/385

This is happening due to a recent change in **knitr**, so if you installed previous knitr version it will work. I'll dig more on why this change and report in https://github.com/yihui/knitr/issues/1901

**Comment by jtrecenti** [comment] 2020-10-02 00:06
Don't know if it's useful, but the code works when we run the chunk with `out.height = "400px"` and `out.width = "400px"`, for example.

**Comment by cderv** [comment] 2020-10-02 08:37
yes, if you set the option on the chunk, it will overwrite the default and works because the issue is with a multiple value option, that is not handle correctly by htmlwidget. Flexdashboard uses by default two values so that the image have another size adapted for mobile viewing. See https://rmarkdown.rstudio.com/flexdashboard/using.html#small_screens

**Comment by TTT12-dumb-dumb** [comment] 2020-10-05 01:16
@jtrecenti @cderv I just updated htmlwidgets and things seem to be working fine now!  Thanks!

**Comment by cderv** [comment] 2020-10-05 10:17
yes this is fixed in last htmlwidget version already released on CRAN 
https://cran.r-project.org/package=htmlwidgets

**Closed** 2021-02-09 18:37 UTC
