### ISSUE TITLE
Flexdashboard is not showing horizontal scroll bar for DT in the browser

### ISSUE THREAD

**Issue by aditya-kothari** [rstudio/flexdashboard#109] opened 2017-02-13 13:10 UTC
Hi Team,

My flexdashboard is not showing horizontal scroll bars for DTs in the BROWSER. It however shows in the R WINDOW after the code is ran. P.S. I have two DTs one below the other and both need to have horizontal scroll bars of their own when I open the dashboard in the browser as well.

Below is the code:

---
title: "hi"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    logo: logo.png
    navbar:
    - {title: "<b>For feedback contact: xxx@</b>", icon: "fa-table", align: right}
runtime: shiny
---

```{r global, setup, include = FALSE}

library(flexdashboard)
library(shiny)
library(plotly)
library(data.table)
library(DT)
library(highcharter)
library(sqldf)
library(rpivotTable)

xxx<-fread("data1.csv")
yyy <-fread("data2.csv")

```

Home

===============================

Row1

-------------------------------

### DT1

```{r}

output$table1 <- renderDataTable({

DT::datatable(yyy, extensions='Scroller', selection = 'single', options = list(pageLength=100, scrollY='400px', scrollX=TRUE, autoWidth=TRUE, searchHighlight=TRUE, scroller=TRUE), filter = 'top', class = "display cell-border")

})

DT::dataTableOutput('table1')


```

Row2

------------------------------

### DT2

```{r}

s = reactive(input$table1_rows_selected)
extractdata <- reactive(subset(xxx, FC == yyy[s(),]$FC & owner == yyy[s(),]$SCAC))

renderDataTable({

DT::datatable(extractdata(), extensions=c('FixedColumns','Buttons', 'ColReorder','Scroller'),
options = list(pageLength=100, scrollY='400px', scrollX=TRUE, autoWidth=TRUE, searchHighlight=TRUE, scroller=TRUE, fixedColumns = list(leftColumns = 3),dom = 'Bfrtip', buttons = list('copy','print', list(extend='collection', buttons= c('csv', 'excel', 'pdf'), text='Download'), I('colvis')), colReorder = TRUE), 
filter = 'top', class = "display cell-border")

})

```

Snapshot of R window:
![r window](https://cloud.githubusercontent.com/assets/24821684/22884463/e0a93b48-f1a9-11e6-932d-10038fd24012.PNG)

Snapshot of Browser:
![browser](https://cloud.githubusercontent.com/assets/24821684/22884469/eb8edce8-f1a9-11e6-8b34-af20bd267192.PNG)

If you see the first snapshot (which is of R window), the horizontal scroll bar seems to be present for both the DTs (which are one below each other). But when I open this is the browser, the horizontal scroll bar is vanished for both the DTs and instead there is one single horizontal scroll bar at the end which I dont want.

I am looking to have both the horizontal scroll bars for DTs separately just like it is in the R window.

Thanks for your time!
Aditya Kothari

**Comment by maxmoro** [comment] 2017-04-13 20:45
I've same issue using Connect, anyone found the solution?

**Comment by tarunparmar** [comment] 2017-11-09 18:43
Hi All,

It looks like the `scrollX` and `scrollY` is not really a boolean input and need value now as per the DT package manual. 
I test with this simple example, hope its helps you too.
```
---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(DT)
library(ggplot2)
```
```
Column {data-width=650}
-----------------------------------------------------------------------
```
```
### Chart A
```
```{r}
datatable(diamonds ,options = list(c(scrollY="200px", scrollX="300px", pageLength = 100)),  filter = 'top')

```

![image](https://user-images.githubusercontent.com/17690950/32623303-b3aace80-c553-11e7-86c9-6a7773c6d043.png)

Reference: https://stackoverflow.com/questions/39775563/r-vertical-scroll-not-working

**Comment by maxmoro** [comment] 2018-01-24 23:50
I still have the problem when the layout is scroll, even with the scrollx='300px'. It works within RStudio, but not on the browser. Anyone has a solution?

`
---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(DT)
library(ggplot2)
```

Inputs {.sidebar}
==============================

Here

we

have

inputs

Body
==============================

Column  
-----------------------------------------------------------------------
### Chart A
```{r}
DT::dataTableOutput('DTtest')

output$DTtest <- DT::renderDataTable(DT::datatable(diamonds[1:1000,] 
                               ,options = list(list(scrollY="300px"
                                                 , scrollX="300px"
                                                 , pageLength = 100
                                                 ))
                               ,  filter = 'top')
)

```


`

**Comment by zhuchcn** [comment] 2018-05-08 20:54
Try adding the code below to your Rmd file. Hope it works!

<style>
    #DTtest{
        overflow: auto;
}
</style>

**Comment by ashley-williams** [comment] 2019-04-15 15:56
I am also having this problem, none of the above fixes have helped.

**Comment by cristianvaldez** [comment] 2019-06-18 21:28
is anyone working on this issue?

**Comment by DanDefATG** [comment] 2019-07-08 13:40
It works for me setting the global options instead of passing the list to the datatable call:

library(DT)
 options(DT.options = list(scrollY="300px",scrollX="300px", pageLength = 100, autoWidth = TRUE))

datatable(data,  filter = 'top')

**Comment by DanDefATG** [comment] 2019-07-08 13:47
Hi, I solved setting global Options instead of passing options to Datatable call.

library(DT)
 options(DT.options = list(scrollY="300px",scrollX="300px", pageLength = 100, autoWidth = TRUE))

datatable(data ,  filter = 'top')

**Comment by zhuchcn** [comment] 2019-07-08 16:27
Or this should work, too. 

```
<style>
.datatables{
    overflow: auto;
}
</style>
```

This allows the width of the datatable to be responsive to the browser width, and if the table content overflows, a scroll bar will be placed at the bottom.  To be noticed that, this will apply to all datatables. If you want to control a particular datatable, do the following, with the specified output ID.

```
#datatable-output-ID{
    overflow: auto;
}
</style>
```

**Comment by wzrzt** [comment] 2019-07-09 18:01
@zhuchcn Execuse me. It seems doen't work in flexdashboard, but works fine in html_document. DT datatable is always wider than div container,  upset...

**Comment by zhuchcn** [comment] 2019-07-09 18:21
@wzrzt Would you like to provide some reproducible code?

**Comment by wzrzt** [comment] 2019-07-09 18:39
@zhuchcn 

---
title: "Test DT width"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll

---


<style>
.datatables{
    overflow: auto;
}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(DT)
library(tidyverse)
library(data.table) 

```

This a DT datatable {data-icon="fa-industry"}
===================================== 

### Table one

```{r cars}

df1 = data.frame(id = 1:26, name = letters, stringsAsFactors = F)

df2 = df1 %>% 
    # filter(id < 4) %>% 
    data.table() %>% 
    dcast( name ~ id )
```

```{r}

df2 %>%
    DT::datatable(
        width = '100%',
        extensions = c( 'Buttons'),
        options = list( 
            dom = 'Bflrtip',
            pageLength = 50, autoWidth=TRUE,
            columnDefs = list(list(width = "0.5px", targets = c(0, 1, 2))),
            buttons = list(list(extend = 'csv',
                                filename = 'down'),
                           list(extend = 'excel',
                                filename = 'down'))
                                       
            ), 
        filter = 'top'
    ) 

```

I expect it to fit with the window, but it shows as flowing:
![image](https://user-images.githubusercontent.com/12440644/60914208-a574f380-a2bb-11e9-9229-dbe8d7ecbe6f.png)

My session_infos:

```
> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS: /opt/microsoft/ropen/3.5.3/lib64/R/lib/libRblas.so
LAPACK: /opt/microsoft/ropen/3.5.3/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] data.table_1.12.2    forcats_0.4.0        stringr_1.4.0        dplyr_0.8.1          purrr_0.3.2          readr_1.3.1         
 [7] tidyr_0.8.3          tibble_2.1.2         ggplot2_3.1.1        tidyverse_1.2.1      DT_0.6               RevoUtils_11.0.3    
[13] RevoUtilsMath_11.0.0

loaded via a namespace (and not attached):
 [1] tidyselect_0.2.5      xfun_0.7              haven_2.1.0           lattice_0.20-38       colorspace_1.4-1     
 [6] generics_0.0.2        htmltools_0.3.6       yaml_2.2.0            rlang_0.3.4           later_0.8.0          
[11] pillar_1.4.1          withr_2.1.2           glue_1.3.1            modelr_0.1.4          readxl_1.3.1         
[16] flexdashboard_0.5.1.1 plyr_1.8.4            munsell_0.5.0         gtable_0.3.0          cellranger_1.1.0     
[21] rvest_0.3.4           htmlwidgets_1.3       evaluate_0.14         knitr_1.23            httpuv_1.5.1         
[26] crosstalk_1.0.0       broom_0.5.2           Rcpp_1.0.1            xtable_1.8-4          promises_1.0.1       
[31] backports_1.1.4       scales_1.0.0          jsonlite_1.6          mime_0.6              hms_0.4.2            
[36] packrat_0.5.0         digest_0.6.19         stringi_1.4.3         shiny_1.3.2           grid_3.5.3           
[41] cli_1.1.0             tools_3.5.3           magrittr_1.5          lazyeval_0.2.2        crayon_1.3.4         
[46] pkgconfig_2.0.2       rsconnect_0.8.13      xml2_1.2.0            lubridate_1.7.4       assertthat_0.2.1     
[51] rmarkdown_1.13        httr_1.4.0            rstudioapi_0.10       R6_2.4.0              nlme_3.1-137         
[56] compiler_3.5.3    
```

**Comment by wzrzt** [comment] 2019-07-09 19:11
Finally, I found a way around, and make it show well and adapt well to window width  in browser windows larger than some resolution, about 1366*768, which is normal size of my colleagues' laptop screen. In browser window less than 1366 width, still my DT datatable wider than flexdashboard page.     
    
I set zoom to 50%, and then font-size to 200%, so the table is smaller but the font size is normal. May be 33% and 300% will make it adapt to smaller browser. But I don't think it necessary for now.  

```
<style>
#DataTables_Table_1_wrapper {
    position: relative;
    clear: both;
    width : 100% !important;
    overflow: auto;
    zoom: 50%;
    font-size: 200%
}
</style>

```

**Comment by zhuchcn** [comment] 2019-07-09 19:28
@wzrzt I'm glad that you figured it out. I just want to add a little. The reason that you are having the problem is the `vertical_layout: scroll` adds an inline css of `flex: 576 576 0px;` to the box (each ###). Not quite sure about its purpose, but I think it's to allow each row being as wide as it needs. If you want to make each row takes the whole width of the window, just adding a {style="width: 100% !important"} to the title of each section (that starts with ###) will work, too. For example:

### Table One {style="width: 100% !important"}

Hope it helps!

**Comment by wzrzt** [comment] 2019-07-09 19:54
@zhuchcn Thank you very much. The table area is as wide as browser now and  Scroller X is available. Now the table looks much better. In fact I'm searching for a way to change columns's width. Each column name is just one letter, still too wide to fit the browser.  ScrollY make it better but it will be perfect if the 26 columns would show in browser window. My 'zoom out and bigger font' solution is just a temporary way. it may work bad in other condition. I think it's better to find a way to define column width or make it narrow automatically to fit the windows. Any suggestions? Defining column width in neither columnDef in options nor formatStyle works.

**Comment by zhuchcn** [comment] 2019-07-09 20:02
@wzrzt I think I had the same question as you and then I just decided to move on and accept the scrollY after trying for a while. Maybe this is something you should ask the DT developers.

**Comment by wzrzt** [comment] 2019-07-10 02:35
@zhuchcn Thank you very much !

**Comment by pinduzera** [comment] 2021-03-23 13:57
I want to add a couple of my findings regarding this issue.
I had a work which was actually working (fitting on the page), and then it suddenly stopped (when I was kniting new  versions)

What i've found is that for some reason DT stopped generating the scroll (i am not sure if it was due a general upgrade.)
But I want to stay clear that the code itself was exactly the same

HTML before (working):
as you can see, it does have that scroll attribute.
![image](https://user-images.githubusercontent.com/14168996/112157888-6806e580-8bc6-11eb-919e-f274f5d1ecc7.png)

HTML after:
For some reason, now it is gone
![image](https://user-images.githubusercontent.com/14168996/112157988-80770000-8bc6-11eb-83e1-c5ccb6aaa253.png)

**Comment by gadenbuie** [comment] 2023-02-24 21:05
It seems this is a duplicate of #84 and @tarunparmar's [answer here](https://github.com/rstudio/flexdashboard/issues/109#issuecomment-343251160) looks like a good resolution for this issue. Thanks all for reporting and please let me know if there's a difference between the two issues.

**Closed by gadenbuie** 2023-02-24 21:05 UTC
