### ISSUE TITLE
read_chunks with shiny not working

### ISSUE THREAD

**Issue by jgonzale** [rstudio/flexdashboard#134] opened 2017-07-13 15:47 UTC
Hi there. First of all, many many thanks for this wonderful package. I'm using it extensively in my day-to-day work.

The situation: to properly organize the source code of a large shiny-based flexdashboard (multipage, lots of info), I decided to follow the instructions detailed in this [webpage](http://zevross.com/blog/2014/07/09/making-use-of-external-r-code-in-knitr-and-r-markdown/).

I put the source code of three dropdown selectors in an external R script. In brief, these three selectors are linked hierarchically, i.e. the first selector contains an initial list, and then when you choose one of the options, the second selector reacts populating its values, and same for the third one.

Then, I "embed" the code be using the `read_chunk` function from the `knitr` package and the `<< x >>`, naming the code chunk with the value in the external script, or even using the `code=readLines(xxx)`. In all cases, when I run the dashboard, what I see is that the first selector if properly populated (as it is statically populated from at the start of the execution), but the other two selectors do not react to the selection of the first one.

Not sure if its is bug or I'm doing something wrong. Any help will be appreciated.

Juan,

PS: I guess that for organization purposes, I'm alligned with requests #81 or #82, but I'm not sure about the status of these features or if they will solve my problem.

**Comment by bborgesr** [comment] 2017-10-10 16:55
Sorry for the late reply! Can you please provide a minimal reproducible example?

**Comment by jcostaexmba2006** [comment] 2018-01-07 18:05
sorry, is ther any solution to this point? i am interested in the same solution
thanks

**Comment by gadenbuie** [comment] 2023-02-24 21:19
Thanks for asking and I'm sorry you haven't had an answer in so long. Part of the problem is that it's hard to tell if there's something that flexdashboard should do differently or if there's a syntax or structural problem in how you're approaching the task. If anyone who has run into this or a similar problem would like to submit a small reproducible example, it would greatly help us to understand the underlying issues. I'm going to close this particular issue, but please feel free to open a new issue if you have a similar use-case!

**Closed by gadenbuie** 2023-02-24 21:19 UTC
