### ISSUE TITLE
the title option cause encoding issue in windows

### ISSUE THREAD

**Issue by unng** [rstudio/flexdashboard#63] opened 2016-06-21 05:17 UTC
the code below can't work as expect, the title in Chinese causes encoding issue in `selectInput`
```
---
title: "无线流量"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---
```
![1](https://cloud.githubusercontent.com/assets/394134/16218635/43c6bfe6-37b2-11e6-9e0d-798e46b14831.png)

but when i change title and it work well.
```
---
title: "uv"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---
```
![2](https://cloud.githubusercontent.com/assets/394134/16218637/4eb656d2-37b2-11e6-9283-0fa0e42cf7ae.png)

**Comment by funnng** [comment] 2016-06-21 05:40
and the subtitle(chunk title) such as `### 流量` will also cause encoding issue, but `### uv` works fine

**Comment by jjallaire** [comment] 2016-07-21 12:39
Could you please provide a full example source file so we can investigate further?

**Comment by funnng** [comment] 2016-07-22 01:18
@jjallaire 
all 3 tests are under window 7: `encoding.issue1.Rmd` and `encoding.issue2.Rmd` has the same encoding problem, `encoding.issue.ok.Rmd` work good.
all these 3 Rmd work good in OS X .

**Comment by jjallaire** [comment] 2016-07-22 01:21
I need a full Rmd source file that exhibits the problem in order to investigate further.

**Comment by funnng** [comment] 2016-07-22 01:24
@jjallaire 
(forget the files last comment, i have problem op paste it as gist please remove the ext name .txt)
all 3 tests are under window 7: `encoding.issue1.Rmd` and `encoding.issue2.Rmd` has the same encoding problem, `encoding.issue.ok.Rmd` work good.
all these 3 Rmd work good in OS X .

[encoding.issue.ok.Rmd.txt](https://github.com/rstudio/flexdashboard/files/377281/encoding.issue.ok.Rmd.txt)
[encoding.issue1.Rmd.txt](https://github.com/rstudio/flexdashboard/files/377280/encoding.issue1.Rmd.txt)
[encoding.issue2.Rmd.txt](https://github.com/rstudio/flexdashboard/files/377282/encoding.issue2.Rmd.txt)

**Comment by jjallaire** [comment] 2016-07-22 10:00
Okay, thanks very much! I've now got this reproducing even within a non-shiny flexdashboard. Here's the code:

    ---
    title: "中文"
    output: flexdashboard::flex_dashboard
    ---

    ```{r setup, include=FALSE}
    library(htmltools)
    ```

    ### 不同渠道之间的流量指数之间请勿比较大小

    ```{r}
    span('不同渠道之间的流量指数之间请勿比较大小')
    ```

    ### Chart 2

    ```{r}
    plot(cars)
    ```

Note that I've saved the file with UTF-8 encoding. 

@yihui and @jcheng5, Any insight on what might be going wrong with the character handling in htmltools?

**Comment by jjallaire** [comment] 2016-07-22 10:01
Note that the characters are rendered fine when they are in the document title or chart title, but only mis-printed within the htmltools::span tag.

**Comment by jjallaire** [comment] 2016-07-22 11:54
It turns out this bug is not specific to flexdashboard (it affects `html_document` as well). Closing this bug in lieu of https://github.com/rstudio/rmarkdown/issues/748

**Closed by jjallaire** 2016-07-22 11:54 UTC
Labels: requires example

**Comment by jjallaire** [comment] 2016-07-22 14:14
@unng It looks like you need to set your locale to Chinese to get this to work, see https://github.com/rstudio/rmarkdown/issues/748#issuecomment-234544073
