### ISSUE TITLE
renderValueBox not appearing

### ISSUE THREAD

**Issue by TCurran4589** [rstudio/flexdashboard#121] opened 2017-05-04 21:42 UTC
Tried implementing a valueBox in my dashboard but nothing is showing up on the rendered html.

Tried using both the static value for valueBox as well as renderValueBox for variable inputs:

`valueBox(test, "Test")
renderValueBox({
  valueBoxOutput(address(), width="100%", height="100%")
  valueBox(address(),
         icon = "fa-trash",
         color ="primary")})`

neither one shows as a value box.

**Comment by cpsievert** [comment] 2021-02-11 16:21
Have you included `runtime: shiny` properly into the yaml matter? Closing since there is no reproducible example so there is no way to know what has gone wrong

**Closed by cpsievert** 2021-02-11 16:21 UTC
