### ISSUE TITLE
Action Button disappears on downsizing window

### ISSUE THREAD

**Issue by pssguy** [rstudio/flexdashboard#53] opened 2016-06-07 19:05 UTC
when i use an actionButton it shows up in full screen but not when reduced in size even when I set a small width eg 100px

Full Screen
![before](https://cloud.githubusercontent.com/assets/2775918/15866488/ad65284a-2c93-11e6-85e2-1dede0cc2e05.png)

Reduced Size
![after](https://cloud.githubusercontent.com/assets/2775918/15866493/b3ded748-2c93-11e6-891e-dc4e1c33139a.png)

**Comment by pssguy** [comment] 2016-06-14 17:47
Just checking in as this kinda goes against pushing FDB as a mobile experience. Am I missing something?

**Comment by jjallaire** [comment] 2016-07-21 15:42
I'm currently not able to reproduce this. Could you provide a minimal reproducible example so we can investigate further?

**Comment by gadenbuie** [comment] 2023-02-24 19:56
Thanks for reporting! I also cannot reproduce this (many years later), so I'm going to close this issue. If you run into something similar, please open a new issue.

**Closed by gadenbuie** 2023-02-24 19:56 UTC
Labels: requires example
