### ISSUE TITLE
Flexdasboard

### ISSUE THREAD

**Issue by mimeides** [rstudio/flexdashboard#104] opened 2017-01-24 12:21 UTC
Hi, Flexdashboard ..; really magic !!!
My question is :  Can we put 2 graphs (vert or Hori) in same tabset 
Example :
.....
Column {.tabset .tabset-fade}
### A
  Graph1  || Graph2
### B
Graph1  
Graph2

Thks a lotssss !!!

Mimeides !

**Comment by jjallaire** [comment] 2017-01-25 13:06
No unfortunately there isn't a way to do this right now.

**Comment by mimeides** [comment] 2017-01-26 16:55
thks a lots !!!!
but   grreatttt   packagee !!!!!

Bye

Mimeides

**Comment by cpsievert** [comment] 2021-02-16 20:24
Duplicate of https://github.com/rstudio/flexdashboard/issues/265

**Closed by cpsievert** 2021-02-16 20:24 UTC
