### ISSUE TITLE
How can I have both the drop down and the icon for my page?

### ISSUE THREAD

**Issue by aditya-kothari** [rstudio/flexdashboard#105] opened 2017-01-27 07:57 UTC
Hi All,

I am wondering if someone can help me use multiple parameters for Pages on flexdashboard.

for example, to declare a new page we use the below code:

NewPage

=========================

now within this page we have option to declare page parameters like orientation, navmenu (for drop downs), page icons etc. But I am unable to use both.

for example the below code doesn't work:

NewPage {data-navmenu="Menu A"} {data-icon="fa-list"}

=============================

How can I have both the drop down and the icon for my page?

**Comment by jjallaire** [comment] 2017-01-27 13:18
You would do it this way:

```
NewPage {data-navmenu="Menu A" data-icon="fa-list"}
```

**Comment by aditya-kothari** [comment] 2017-01-28 07:35
Hi,

Thanks for the quick response but doing this is inserting icons for the pages that are in the drop down. I need the icon for "Menu A" and not "New Page". See below snapshot:

![capture](https://cloud.githubusercontent.com/assets/24821684/22395130/15e911b6-e4e9-11e6-8f78-0562ca6ece48.PNG)

And here is the sample code used:

---

title: "Page Navigation Menus"
output: flexdashboard::flex_dashboard

---

Page 1 {data-navmenu="Menu A" data-icon="fa-list"}

=====================================


Page 2 {data-navmenu="Menu A" data-icon="fa-list"}

=====================================  


Page 3 {data-navmenu="Menu B"}

=====================================


Page 4 {data-navmenu="Menu B"}

=====================================

**Comment by jjallaire** [comment] 2017-01-28 11:46
Sorry about that, there is actually no way currently to set an icon for the menu.

**Comment by aditya-kothari** [comment] 2017-01-28 13:34
No problem. BTW is there a new version of flexdashboard releasing anytime in the future?

**Comment by jjallaire** [comment] 2017-01-28 14:46
It looks like the are a couple of bugs fixed on master that we don't yet have on CRAN so we'll do a release for those soon. Is there anything else you are looking for in a new release?

**Comment by aditya-kothari** [comment] 2017-01-30 07:12
If you would be able to add the below to the newest release that would be great:

* Collapsible sidebar (just like Shiny)
* Notifications on the top right side of navigation bar (like alerts, messages e.t.c)
* And obviously the option to set icons for the menu. ;)

Thanks a lot for asking! :)

**Comment by jjallaire** [comment] 2017-01-30 11:12
Those features aren't likely to make it into flexdashboard soon (all good ideas of course) mostly because they are well covered by shinydashboard (which in general provides much higher fidelity control over UI at the expense of some additional code).

**Comment by dsaada** [comment] 2019-12-11 13:51
hello,

any update on this?

**Comment by cpsievert** [comment] 2021-02-16 19:29
Seems this is a duplicate of https://github.com/rstudio/flexdashboard/issues/88

**Closed by cpsievert** 2021-02-16 19:29 UTC

**Comment by AnotherDataGuy** [comment] 2021-06-30 06:05
A workaround for this issue might be adding Unicode icons to the data-navmenu :

Page 1 {data-navmenu="🕮 Menu A" data-icon="fa-list"}

=====================================

Page 2 {data-navmenu="🕮 Menu A" data-icon="fa-list"}

=====================================

Page 3 {data-navmenu="� Menu B"}

=====================================

Page 4 {data-navmenu="� Menu B"}

=====================================

See https://www.utf8icons.com/ for a complete list

**Comment by ambarja** [comment] 2022-01-18 02:47
Is it currently possible to do this?
