### ISSUE TITLE
selectInput does not delete a selection

### ISSUE THREAD

**Issue by vdejager** [rstudio/flexdashboard#256] opened 2020-03-23 15:59 UTC
I'm new to flexdashboard.

I'm trying to build a flexdashboard where I can select the columns to show. I can only _add_ to the select box, but not _delete_ a selected item from the selection, despite what the docs say.
double clicking on a selected item should delete it if I understand correctly.
Any hints how to get this working?

```
###############
# in the side bar.
#columns_to_show
all_columns=colnames(snv_hcdiffs_filtered)
column_select=c('Chromosome','Startposition','End position','Reference','Variant','Gene name', 'Genecomponent','Protein Effect')

selectInput("columns", "columns", all_columns, selected = column_select, multiple = TRUE, selecttize=TRUE,
 width = NULL, size = NULL)
# reactive
react_columns<- reactive({
  input$columns
})
```

**Comment by cderv** [comment] 2020-03-23 21:21
In your code, I see `selecttize=TRUE` instead of `selectize=TRUE`. maybe it can cause issue. 

Can you provide a reproducible example ? It will help to understand the issue. 

This works fine for me: I can select several months and delete them from the selection by selecting and using SUPPR or BACKSPACE

````r
---
title: "test"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r global, include = FALSE}
library(flexdashboard)
library(shiny)
```

Column {.sidebar}
----------------------------------------------------

```{r}
selectInput(
  "month", 
  label = "Pick a Month",
  choices = month.abb, 
  multiple = TRUE,
  selected = month.abb[2]
)

getmonth <- reactive({
  sprintf('Number selected is %d', length(input$month))
})

renderText({getmonth()})
```
````

Hope it helps

**Comment by cpsievert** [comment] 2021-02-16 19:31
Closing since there's no reproducible example

**Closed by cpsievert** 2021-02-16 19:31 UTC
