### ISSUE TITLE
Reactive plots disappear after browser window refresh

### ISSUE THREAD

**Issue by AnatolyVuets** [rstudio/flexdashboard#164] opened 2017-12-06 13:12 UTC
Hello, flexdashboard team! 
I would appreciate any help on the following issue: 
Reactive plots disappear when I refresh my dashboard page in browser. 
I'm using the most recent development versions of flexdashboard, shiny and plotly.
RStudio v 1.1.383; R v 3.4.3

Code example:
```{r}
## some data preparations 

 renderPlotly({
selectedData() %>%
  plot_ly(x = ~funnel_ymd, y = ~value, color = ~variable, colors = "Dark2",
          yaxis = ~paste0("y", id)) %>%
  add_bars() %>%
  subplot(nrows = 14, shareX = TRUE)
})
```

However, analogous non-reactive plot does not suffer from this issue:

```{r}
## some data preparations 
constData %>%
  plot_ly(x = ~funnel_ymd, y = ~value, color = ~variable, colors = "Dark2",
          yaxis = ~paste0("y", id)) %>%
  add_bars() %>%
  subplot(nrows = 14, shareX = TRUE)

```

**Comment by dwall1** [comment] 2018-02-27 10:34
Did you ever find a way to resolve this issue? I'm experiencing something similar withmy flexdashboard app

**Comment by AnatolyVuets** [comment] 2018-02-28 12:34
dwall1, unfortunately I did not manage to solve this problem and ended up using Shiny Dashboard which if more flexible and rich in options. I would recommend you to try it

**Comment by dwall1** [comment] 2018-03-05 09:39
Thanks for letting me know

**Comment by Ljupch0** [comment] 2019-11-14 20:26
I'm having the same issue on all of my flexdashboard runtime:shiny apps. Any update?

**Comment by Ljupch0** [comment] 2019-11-14 20:27
It seems that shinydashboard is the way to go.

**Comment by dvictori** [comment] 2020-05-13 20:20
I'm also facing this issue in a flexdashboard that connects to a Postgres database. Has anyone solved this?

**Comment by dvictori** [comment] 2020-05-14 12:39
I've found out what is causing the problem. In my original flexdashborad, when I added `runtime: shiny`, the text was indented at the same level of the `output` block. So when I reloaded the flexdashboard - even in RStudio viewer - the rendered outputs would stop working. 

When I removed the indentation from `runtime:shiny`, things got back to normal. So for anyone having this issue, check your indentation on the YAML at the top of the document.

**Comment by cpsievert** [comment] 2021-02-16 20:21
Closing due to lack of a reproducible example

**Closed by cpsievert** 2021-02-16 20:21 UTC

**Comment by JosephCrispell** [comment] 2021-04-21 11:18
Thank you @dvictori - that worked perfectly for me! Been smacking my head against this one for the last hour!?!?!
