### ISSUE TITLE
dynamic title stopped working 

### ISSUE THREAD

**Issue by djouallah** [rstudio/flexdashboard#207] opened 2019-01-03 00:26 UTC
RStudio
Version 1.2.1206
© 2009-2018 RStudio, Inc.
Build 1245 (96fb791)
windows 10, 64 bits

I have being using the code to render a dynamic title in flexdashboard for the last couple of months with no problem, after updating to the last preview, the title does not show up instead i get this

summary.utf8.md ( summary is the rmd file name)

my RMDcode is

```
---
output:
  flexdashboard::flex_dashboard: default
  html_document: default
---

   ``'{r}
     r code to get the values of title_Var
     title_Var <- paste("Numurkah", format(max(Data$`Cutt Off daily`), "%d %b %Y"))
   ``'
 ---
title:  `r title_Var`
 ---

```

**Comment by gabovailati** [comment] 2019-05-21 08:39
I have the same issue. After updating RStudio with the latest release (Version 1.2.1335 - Build 1351 (f1ac3452)), the dynamic title stopped working.

---
title: `r paste('Dashboard -', var)`
---

**Comment by gadenbuie** [comment] 2023-02-28 21:02
I believe this is a duplicate of https://github.com/rstudio/flexdashboard/issues/226 (or vice-versa) and is now fixed with recent versions of rmarkdown. Thanks for reporting!

**Closed by gadenbuie** 2023-02-28 21:02 UTC
