### ISSUE TITLE
htmlwidgets unreliable

### ISSUE THREAD

**Issue by daniel-matthews** [rstudio/flexdashboard#35] opened 2016-05-26 09:24 UTC
I have a flexdashboard that contains a large number of html widgets - dygraphs, datatables, gauges  and d3heatmaps. Whenever I knit the code, the number of html widgets that actually render in the output ranges from all, to less than half (the dygrpahs being the most reliable, and the dashboard gauges the least). This is the same code, with the same data simply run 30 seconds later.  Is this because I'm trying to create too many at once (all in its > 100 across 40 pages)? If so is there any plan to make it easier to output multiple html files with a common menu?

**Comment by jjallaire** [comment] 2016-05-26 09:33
We've never tried 100 widgets and 40 pages! You might indeed be bumping up
against a practical limit here.

What is the output in the JavaScript console when widgets fail to render?

Multiple html files with a common menu is a good idea. This might require
that we build an R Markdown site engine though, which will take some
considerable work.

**Comment by daniel-matthews** [comment] 2016-05-26 09:50
I suspected that might be the case. The pages are generated via a loop, but Ive tried a none-loop version and I get the same result. The error I get is: TypeError: x.data is undefined.

**Comment by jjallaire** [comment] 2016-05-26 09:53
That indicates an error in marshaling the data from R to a widget. If it's
intermittent then perhaps there is an out of memory condition?

**Comment by daniel-matthews** [comment] 2016-05-26 10:05
Sorry to ask (and I realise we are now slightly off topic).. but what (if anything) can I do about that? (I'm running 64 bit R on windows)

**Comment by jjallaire** [comment] 2016-05-26 12:24
I don't know for sure whether it's memory or not but it seems like a
definite possibility. I don't know if there is anything which can be done
about that.

**Comment by tbadams0405** [comment] 2016-05-31 13:04
@jjallaire, I'm about to implement a Shiny project in fleshdashboards, and while I don't have 100 graphs, I could envision a scenario when I have ~20. Have you ever implemented a project with this many graphs/htmlwidgets?

**Comment by daniel-matthews** [comment] 2016-05-31 16:05
@tbadams0405 - My project works fine when I reduce the number of charts to around 50. I don't drive it using shiny though (its static). If anything I imagine shiny will cope better - Ive built a very large system in shiny before (using Shiny Dashboard, not Flexdashboard). All signs point to memory being the issue (so the exact point you struggle will depend on your setup).

**Comment by tbadams0405** [comment] 2016-05-31 17:13
@daniel-matthews Ok, got it. Thanks for the info!

**Comment by ejoranlienea** [comment] 2016-07-11 18:10
@jjallaire 
We ran up against a similar problem with a large number of widgets across many pages. Instead of not displaying, however, we had tables appearing in the wrong place.

What we found out is that if an htmlwidget is not assigned a name upon creation, it is given a random name, like so: `id <- paste("htmlwidget", as.integer(stats::runif(1, 1, 10000)), sep="-")`.
With a large number of widgets, this will occasionally lead to elements with the same ID, which causes a table to display the wrong content (and would likely break a widget if they were not of the same type). It also explains why the problem is so hard to trace: unless you're setting a seed, the duplicated names will occur randomly.

As a temporary fix, we forked the htmlwidgets package, and increased the size of the uniform interval, but this only reduces the chance of error. It would be great if flexdashboard would allow unique names to be assigned to created widgets.

**Comment by jjallaire** [comment] 2016-07-12 12:54
@jcheng5 What would you think of using uuid's (via https://cran.r-project.org/web/packages/uuid/index.html) rather than stats::runif here?

**Comment by jjallaire** [comment] 2016-07-12 14:40
Here's a PR which uses **uuid** for unique IDs: https://github.com/ramnathv/htmlwidgets/pull/213

@jcheng5 @ramnathv @timelyportfolio

**Comment by jjallaire** [comment] 2016-07-21 13:57
Fixed via https://github.com/ramnathv/htmlwidgets/pull/213

**Closed by jjallaire** 2016-07-21 13:57 UTC
