### ISSUE TITLE
Won't knit when ggsurvival plot

### ISSUE THREAD

**Issue by zbdoh1** [rstudio/flexdashboard#285] opened 2020-09-30 14:19 UTC
Hi all,

I recently tried to run some code (hadn't run it in about 1 month) and it's failing to knit. When I run the code in normal R or in R markdown  it creates my survival curve without issue, so I think it's specific to flexdashboard. 

The error it is throwing says:
Error in validateCssUnit(sizeInfo$width) : 
  CSS units must be a single-element numeric or character vector
Calls: <Anonymous> ... <Anonymous> -> need_screenshot -> toHTML -> validateCssUnit
Execution halted

Here is my minimal code:

`---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(ggplot2)
library(plotly)
library(plyr)
library(flexdashboard)
library(readr)
library(survival)
library(ggplot2)
library(dplyr)
library(ggfortify)
library(survival)
library(survminer)
library(tidyr)
library(readxl)
library(scales)
library(ggiraph)
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

curve <- km_curve$plot + scale_x_continuous(breaks = c(0:11), expand = c(0,0)) + scale_y_continuous( breaks = c(0.5,.6,.7,.8,.9,1), label = scales::percent_format(accuracy = 1), expand = c(0,0)) + geom_abline(intercept=1, slope=slope*(.01), color = 'black', linetype="dashed")

p <- curve + theme(legend.position = "bottom") + coord_cartesian(ylim = c(0.50,1),xlim=c(0,11))

p <- ggplotly(p, tooltip = c("time","surv"))

for (i in 1:length(p$x$data)){
  if (!is.null(p$x$data[[i]]$name)){
    p$x$data[[i]]$name =  gsub("\\(","",strsplit(p$x$data[[i]]$name,",")[[1]][1])
  }
}
p
```

`

**Comment by cderv** [comment] 2020-10-01 09:01
This is a known issue between htmlwidgets and flexdashboard

Duplicate of https://github.com/rstudio/flexdashboard/issues/282 and https://github.com/yihui/knitr/issues/1901

A fix in the way in **htmlwidgets** in https://github.com/ramnathv/htmlwidgets/pull/387

should be release on CRAN very soon to fix this. 

For now, you can install previous version of **knitr** 1.29

**Comment by cderv** [comment] 2020-10-05 10:21
you can now install the last version of htmlwidget already on CRAN to make it work again.
https://cran.r-project.org/package=htmlwidgets

**Closed** 2021-02-09 18:37 UTC
