### ISSUE TITLE
Shiny inputs cause all screens to run on load

### ISSUE THREAD

**Issue by nite** [rstudio/flexdashboard#58] opened 2016-06-17 09:34 UTC
If you add any input to a flexdashboard, then lazy loading of screens is broken - run the following and you'll see 'rendering Screen 2' on load. Comment out the selectInput and it goes away. 

`---
title: "Test FlexDashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    horizontal_layout: fill
## runtime: shiny
# Screen 1

``` r
selectInput('a', label = 'A', choices = c('a','b'))
renderText({
  print('rendering Screen 1')
  'Screen 1'
})
```
# Screen 2

``` r
renderText({
  print('rendering Screen 2')
  'Screen 2'
})
```

`

**Comment by jcheng5** [comment] 2016-07-21 16:50
@nite I'm not reproducing this--can you please try again with the github master version of flexdashboard, and either the CRAN or github master version of shiny?

**Comment by jcheng5** [comment] 2016-07-21 20:41
@nite I just realized I had a conversation with you over email about this where I asked you to file this issue. Thanks for filing it. :) I can't reproduce this issue anymore using the example you sent me over email, so hopefully the same will be true for you.

**Comment by gadenbuie** [comment] 2023-02-24 20:00
Thanks again for opening this issue! Since it seems this problem has either been resolved or hasn't re-appeared, I'm going to close this issue.

**Closed by gadenbuie** 2023-02-24 20:00 UTC
Labels: shiny
