### ISSUE TITLE
Data Height Minimum

### ISSUE THREAD

**Issue by geoffreylarnold** [rstudio/flexdashboard#169] opened 2018-01-03 15:09 UTC
Flexdashboard appears to lack the functionality to easily set a minimum height for rows through the data-height argument. Possibly also for width for anyone using column setups.

**Comment by gadenbuie** [comment] 2023-02-24 21:44
Thanks for the question. It turns out you can add `style="min-height: 250px"` inside the row attributes:

```
Row {data-height=900 style="min-height:250px"}
--------------------------------------
```

I know that the resulting row will have the desired minimum height style, but I'm not sure exactly how that will play out in the dashboard layout. It'd be helpful if you could provide a reproducible example illustrating your use case.

I'm going to close this issue now, but I'd be happy to reopen it if I've missed something.

**Closed by gadenbuie** 2023-02-24 21:44 UTC
