### ISSUE TITLE
NO full height when using ggplotly

### ISSUE THREAD

**Issue by MAGALLANESJoseManuel** [rstudio/flexdashboard#355] opened 2021-08-16 17:43 UTC
I do not why my ggplotly output does not occupy the whole plot area!
![image](https://user-images.githubusercontent.com/7110381/129606582-7ca26db5-141d-49ba-9d2d-84ee1826a890.png)

**Comment by lz100** [comment] 2021-09-10 02:32
```r
plotlyOutput(
  outputId,
  width = "100%",
  height = "400px",
  inline = FALSE,
  reportTheme = TRUE
)
```
plotlyOutput by default has a fixed height of 400px, of course it will not take the whole height. Change it to `100%` may help (never tested it).

**Comment by cpsievert** [comment] 2021-09-20 20:39
Closing due to lack of a reproducible example.

**Closed by cpsievert** 2021-09-20 20:39 UTC
